---
# This playbook deploys the Nginx web server on hosts

- name: configure and deploy the Nginx to all site nodes
  gather_facts: no
  hosts: site
  remote_user: ubuntu
  become: yes
  roles:
    - presetup  
    - install-nginx