---

- name: install nginx 
  apt:
    name: nginx
    state: latest

- name: Copy simple index html to nginx default page
  copy:
    src: index.html
    dest: /var/www/html
  tags:
  - update_ui    

- name: start nginx service
  service:
    name: nginx
    state: started
    
- name: Allow nginx ports
  ufw:
    rule: allow
    name: Nginx HTTP